### PR TITLE
Podcast: add episode 2

### PR DESCRIPTION
**Pull request by bitschmidty**
Note: there is a fixme in the iframe embed of the player since this podcast is scheduled to be released on anchor.fm on Nov 24. I will need to get the URL for the embed at that time.

Edited podcast audio file can be listened to here for review:
https://www.dropbox.com/s/cublocymj1t02w6/Brink%20Technology%20Ancestors.mp3?dl=0

### CODE REVIEW

**Comment by glozow** [comment]
LGTM, thanks @bitschmidty !

**Comment by jnewbery** [comment]
ACK. Thanks Mike!

**Review by jnewbery — COMMENTED** [review]
ACK. Thanks Mike!

**Comment by jnewbery** [comment]
Thanks Mike!

**Pull request merged**
