### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by bitschmidty**

### CODE REVIEW

**Comment by bitschmidty** [comment]
@jnewbery @einotna feeling blue? take a look

**Comment by einotna** [comment]
New styling of the buttons look great.

Re color of links and buttons: The original red links look nice, and are part of the original brand color scheme. What are our thoughts on red links and blue buttons? Or muting the red on the buttons to either #ff7f7f or #ff9999 or some other tint?

The blue links changes the website feel.

**Comment by bitschmidty** [comment]
Afaict red was more "random" choice and less deliberate branding choice, but that’s a @jnewbery thang. But either way, we can choose what is best for next.

I can whip up a less fear-inducing red button and send over a screenshot for review.

**Comment by jnewbery** [comment]
Definite improvement. Thanks Mike.

I agree with @einotna that we should keep red for the links. There wasn't a huge amount of thought put into it initially, except that I thought it looked quite nice against the off-white background. Red for buttons is too much - blue, green or muted red seem reasonable to me.

New width is mostly good. I think the blog pages are a bit too narrow now, since the #post-author panel on the left takes up quite a lot of the width.

**Comment by bitschmidty** [comment]
Here are a few options of button colors in addition to blue
Screen Shot 2021-04-21 at 9 52 09 AM
Screen Shot 2021-04-21 at 9 51 35 AM
Screen Shot 2021-04-21 at 9 51 11 AM
Screen Shot 2021-04-21 at 9 50 52 AM

Pushed commits for going back to red, and another for widening the blog post page.

**Comment by jnewbery** [comment]
Looks great. Thanks Mike!

**Pull request merged**
