### PR TITLE
Adds twitter calls to action

### PR DESCRIPTION
**Pull request by bitschmidty**
Per @einotna's suggestion.

Dont love the footer, but it works. If better ideas, have at it.

### CODE REVIEW

**Comment by einotna** [comment]
ack, thank you!

**Comment by bitschmidty** [comment]
Added some more space between the handle and email in the footer and customized the footer's responsiveness accordingly.

**Comment by jnewbery** [comment]
Looks good, apart from on a 1024px width display:

image

Maybe add a bit of margin to the right of the first block?

**Comment by bitschmidty** [comment]
@jnewbery take a look now

**Pull request merged**
