### PR TITLE
add homerun links with buttons

### PR DESCRIPTION
**Pull request by einotna**
before merging, we can chat in sync about the lay out of the application forms and if we like the button idea as a call to action.

### CODE REVIEW

**Comment by bitschmidty** [comment]
I pushed a commit to fixup some of the html for the buttons

**Comment by bitschmidty** [comment]
@einotna Thanks for getting this setup!

Some feedback on the Grant application process:

I think github should be top of the links on first page with the other links. Can probably take out linkedin.

Add validation to questions on second page while you are on the page.  You can submit a blank form now but it then gives a weird error message when you are done.

The back to job application button could ideally go back to our website instead of a duplicate content page on the homerun website.

Satoshi's last name question had a validation on it to try and prevent spam submissions on the google form. Is there an equivalent/better spam prevent mechanism for homerun?

Similar feedback on the fellow application.

**Comment by jnewbery** [comment]
I've pushed some minor tweaks. Looks great, thanks @einotna!

**Comment by jnewbery** [comment]
As a follow-up, it'd be nice to style the buttons with something like https://getbootstrap.com/docs/4.0/components/buttons/.

**Pull request merged**
