### PR TITLE
Sponsors: add Silvergate

### PR DESCRIPTION
**Pull request by bitschmidty**

### CODE REVIEW

**Comment by jnewbery** [comment]
A couple of suggested changes to the logo:

image

- it's inside a frame, so change the background to white instead of transparent
- remove the redundant word and just have the logo (silvergate is written below)

I also think we should have a 'service providers' section, and show that Silvergate is our banking partner. It'd be good to show gratitude for the free service.

**Comment by bitschmidty** [comment]
Ill work with their marketing team to make sure they are ok with these logo changes

**Comment by jnewbery** [comment]
> Ill work with their marketing team to make sure they are ok with these logo changes

I think it'd be a logo change to change the background to beige (which is effectively what happens if we use a transparent background.

**Comment by bitschmidty** [comment]
They specifically recommended this approved logo image for our page after I
initially sent a logo only no text on white background the other day. So
just want to make sure they sign off on it.

**Comment by jnewbery** [comment]
The logo is 4.8MB. Can you slim it down a little :grimacing:?

**Comment by bitschmidty** [comment]
They are on board, approved. Rebased on master and changed the image.

Checking with Silvergate marketing on any promotion they might want to do.

**Comment by bitschmidty** [comment]
Yeah, woops much too big. Shrank it.

**Comment by jnewbery** [comment]
Thanks Mike!

Any thoughts about this:

> I also think we should have a 'service providers' section, and show that Silvergate is our banking partner. It'd be good to show gratitude for the free service.

**Comment by bitschmidty** [comment]
> Any thoughts about this:
> 
> > I also think we should have a 'service providers' section, and show that Silvergate is our banking partner. It'd be good to show gratitude for the free service.

Yeah, good idea to add that section with Silvergate. Ill also get a list of other providers to consider and will push commits here later this week.

**Comment by bitschmidty** [comment]
@jnewbery added Service Providers section to the sponsors page. Can you check with your marketing contact at NYDIG on the logo?

**Comment by jnewbery** [comment]
Made some tweaks to the logo.

**Comment by bitschmidty** [comment]
ACK on the text changes

**Comment by bitschmidty** [comment]
@jnewbery rebased on master and squashed

**Comment by jnewbery** [comment]
Thanks Mike. We're currently waiting for approval from NYDIG for this.

**Comment by jnewbery** [comment]
LGTM. Thanks Mike!

**Pull request merged**
