### PR TITLE
Remove tweet link from blog template

### PR DESCRIPTION
**Pull request by bitschmidty**
1. I dont like it
2. It doesn’t appear to work
3. I dont think people use such links
4. It simplifies the template

Closes https://github.com/bitcoinbrink/website/issues/16

### CODE REVIEW

**Comment by harding** [comment]
FYI, the link on the current website currently works for me:



However, I agree with reasons 1, 3, and 4.

**Comment by jnewbery** [comment]
Great. I agree that probably no-one uses these things.

**Comment by jnewbery** [comment]
Can we remove the "https://platform.twitter.com/widgets.js" script as well?

**Comment by bitschmidty** [comment]
@harding weird that it worked for you, but I wont let my curiosity of why that is slow me down!

@jnewbery I have removed the script include (which I dont think was doing anything for the site even before this PR), and site looks ok smoke testing without it

Pushed a commit that has the link removed and the widget import removed

**Pull request merged**
