### PR TITLE
Add media page

### PR DESCRIPTION
**Pull request by bitschmidty**
- adds media page per https://github.com/bitcoinbrink/website/issues/18
- adds a title to the blog page
- styles blog and media page lists for better alignment

Closes https://github.com/bitcoinbrink/website/issues/18

### CODE REVIEW

**Comment by jnewbery** [comment]
This is a great start. Thanks @bitschmidty. I've pushed a commit that sketches out some proposed style changes. The main change is to include images for the outlets, which makes it a lot quicker to skim through the stories.

The commit is just a sketch and needs some work - moving styles into CSS, making sure it's reactive, and adding images for the remaining stories. Let me know what you think.

**Comment by bitschmidty** [comment]
Concept ACK on the suggestions of:

- adding images for the outlets (and standardizing on the square shape)
- pulling outlet out of titles

I had a local commit with images on this and Ill resurrect that and will revise for this week, stay tuned.

**Comment by jnewbery** [comment]
Some more to add:

- [ ] Bitcoin Magazine podcast: https://bitcoinmagazine.com/technical/interview-developing-bitcoin-with-john-newbery
- [ ] Coinscrum: https://www.coinscrum.com/discussing-bitcoin-core-devs-in-a-bull-market-with-john-newbery/
- [ ] (upcoming) interview with Gloria Zhao on the Bitcoin Magazine podcast

**Comment by bitschmidty** [comment]
Pushed a commit which adds media images, associated styling, and additional media news entries
@jnewbery

**Comment by jnewbery** [comment]
This is a great improvement. Thanks @bitschmidty!

For narrower displays (tablets, phones), what do you think about doing center-aligning, ie:

image

instead of:

image

and perhaps also scaling the publication's image down a bit?

**Comment by jnewbery** [comment]
Beautiful!

**Pull request merged**
